import { z } from 'zod';
import { DatingStatKeySchema, RelationshipStatKeySchema } from '../stats';

/**
 * Minigame framework schemas.
 *
 * Security model: the client only ever submits raw PERFORMANCE METRICS
 * (e.g. pairs matched, timing accuracy, chosen answers). The server holds the
 * authoritative answer keys / scoring formulas and computes the score, grade,
 * and rewards. The client can NEVER supply stat deltas or money.
 */

export const MINIGAME_IDS = [
  'memory_match',
  'timing_meter',
  'lore_quiz',
  'sweet_and_sour',
  'two_truths_a_lie',
  'rhythm_serenade',
  'lumberjack',
  'writer',
] as const;
export const MinigameIdSchema = z.enum(MINIGAME_IDS);
export type MinigameId = z.infer<typeof MinigameIdSchema>;

export const GradeSchema = z.enum(['S', 'A', 'B', 'C', 'D', 'F']);
export type Grade = z.infer<typeof GradeSchema>;

/** Reward bundle produced server-side from a minigame run. */
export const MinigameRewardSchema = z.object({
  dating: z.record(DatingStatKeySchema, z.number().int()).default({}),
  relationship: z.record(RelationshipStatKeySchema, z.number().int()).default({}),
  money: z.number().int().default(0),
});
export type MinigameReward = z.infer<typeof MinigameRewardSchema>;

/**
 * A short, deterministic in-character reaction shown on the result screen. The
 * SERVER composes it (no LLM) from the grade + character; the client only
 * renders it, tone-tinted.
 */
export const MinigameReactionSchema = z.object({
  line: z.string(),
  tone: z.enum(['delighted', 'warm', 'playful', 'neutral', 'disappointed']),
});
export type MinigameReaction = z.infer<typeof MinigameReactionSchema>;

// --- Per-game start configs (server -> client) ------------------------------

export const MemoryMatchCardSchema = z.object({
  id: z.string(),
  /** Display text shown on the card face. */
  label: z.string(),
  /** Cards sharing the same pairKey form a matching pair. */
  pairKey: z.string(),
  /** Display hint only (the cue vs its reveal) — NEVER an answer key. */
  face: z.enum(['cue', 'reveal']).optional(),
});
export type MemoryMatchCard = z.infer<typeof MemoryMatchCardSchema>;

export const MemoryMatchConfigSchema = z.object({
  cards: z.array(MemoryMatchCardSchema),
  totalPairs: z.number().int().positive(),
  /** Board size, scaled to how close you are. */
  difficulty: z.enum(['cozy', 'spark', 'deep']).default('spark'),
});
export type MemoryMatchConfig = z.infer<typeof MemoryMatchConfigSchema>;

/** One round of the timing meter — difficulty escalates across rounds. */
export const TimingRoundSchema = z.object({
  /** Target zone as [0..1] positions along the meter. */
  targetStart: z.number().min(0).max(1),
  targetEnd: z.number().min(0).max(1),
  /** Sweep speed for this round (units per second). */
  speed: z.number().positive(),
});
export type TimingRound = z.infer<typeof TimingRoundSchema>;

export const TimingMeterConfigSchema = z.object({
  rounds: z.array(TimingRoundSchema).min(1).max(20),
});
export type TimingMeterConfig = z.infer<typeof TimingMeterConfigSchema>;

export const QuizQuestionSchema = z.object({
  id: z.string(),
  prompt: z.string(),
  choices: z.array(z.string()).min(2).max(6),
});
export type QuizQuestion = z.infer<typeof QuizQuestionSchema>;

export const LoreQuizConfigSchema = z.object({
  questions: z.array(QuizQuestionSchema).min(1),
  /** Whether the questions were generated by the LLM or came from fallbacks. */
  source: z.enum(['llm', 'fallback']),
});
export type LoreQuizConfig = z.infer<typeof LoreQuizConfigSchema>;

// sweet_and_sour — sort trait cards into Adore / Can't-stand / Doesn't-mind.
export const SweetSourTraySchema = z.object({
  key: z.enum(['adore', 'avoid', 'meh']),
  label: z.string(),
});
export const SweetSourCardSchema = z.object({ id: z.string(), label: z.string() });
export const SweetAndSourConfigSchema = z.object({
  cards: z.array(SweetSourCardSchema).min(6).max(18),
  trays: z.array(SweetSourTraySchema).length(3),
  source: z.enum(['llm', 'fallback']),
});
export type SweetAndSourConfig = z.infer<typeof SweetAndSourConfigSchema>;

// two_truths_a_lie — spot the bluff among three statements, with a wager.
export const TwoTruthsStatementSchema = z.object({ id: z.string(), text: z.string() });
export const TwoTruthsRoundSchema = z.object({
  id: z.string(),
  statements: z.array(TwoTruthsStatementSchema).length(3),
});
export const TwoTruthsConfigSchema = z.object({
  rounds: z.array(TwoTruthsRoundSchema).min(1).max(8),
  source: z.enum(['llm', 'fallback']),
});
export type TwoTruthsConfig = z.infer<typeof TwoTruthsConfigSchema>;

// rhythm_serenade — stay in time with a scrolling beat pattern.
export const RhythmSlotSchema = z.object({
  index: z.number().int().min(0),
  /**
   * beat vs rest. Necessarily shipped to the client so it can render the lanes and
   * play (a timing game must show its pattern); the server grades against its own
   * beatSlots/restSlots derived from these same values and trusts client offsets.
   */
  kind: z.enum(['beat', 'rest']),
  laneHint: z.number().int().min(0).max(3),
});
export const RhythmSerenadeConfigSchema = z
  .object({
    bpm: z.number().positive(),
    leadInMs: z.number().int().min(0),
    beatCount: z.number().int().min(8).max(32),
    hitWindowMs: z.number().positive(),
    slots: z.array(RhythmSlotSchema).min(8).max(32),
    themeLabel: z.string(),
  })
  .refine((c) => c.slots.length === c.beatCount, { message: 'slots length must equal beatCount' });
export type RhythmSerenadeConfig = z.infer<typeof RhythmSerenadeConfigSchema>;

// lumberjack — a money-only SKILL JOB (no character/relationship). Time each axe
// swing into the log's "grain" zone; the zone narrows and the swing quickens with
// every log as your arms tire. Same sweep chassis as timing_meter, but graded on a
// server-derived combo, and it pays coin instead of building a bond.
export const LumberjackLogSchema = z.object({
  /** The grain "sweet spot" as [0..1] positions along the swing arc. */
  targetStart: z.number().min(0).max(1),
  targetEnd: z.number().min(0).max(1),
  /** Swing speed for this log (units per second) — ramps up as you tire. */
  speed: z.number().positive(),
});
export type LumberjackLog = z.infer<typeof LumberjackLogSchema>;

export const LumberjackConfigSchema = z.object({
  logs: z.array(LumberjackLogSchema).min(1).max(20),
});
export type LumberjackConfig = z.infer<typeof LumberjackConfigSchema>;

// writer — a money-only SKILL JOB: transcribe a short, world-flavored newspaper
// dispatch verbatim. The copy is LLM-written (with a deterministic fallback) and
// graded on typing precision + speed. The passage is sent to the client to type,
// but the server keeps its own copy as the answer key and scores the submission.
export const WriterConfigSchema = z.object({
  /** A flavor headline shown above the copy. */
  headline: z.string().default(''),
  /** The passage the player must transcribe, verbatim. */
  passage: z.string().min(1),
  /** Whether the copy was LLM-written or assembled from a deterministic fallback. */
  source: z.enum(['llm', 'fallback']),
});
export type WriterConfig = z.infer<typeof WriterConfigSchema>;

export const MinigameConfigSchema = z.discriminatedUnion('minigameId', [
  z.object({ minigameId: z.literal('memory_match'), config: MemoryMatchConfigSchema }),
  z.object({ minigameId: z.literal('timing_meter'), config: TimingMeterConfigSchema }),
  z.object({ minigameId: z.literal('lore_quiz'), config: LoreQuizConfigSchema }),
  z.object({ minigameId: z.literal('sweet_and_sour'), config: SweetAndSourConfigSchema }),
  z.object({ minigameId: z.literal('two_truths_a_lie'), config: TwoTruthsConfigSchema }),
  z.object({ minigameId: z.literal('rhythm_serenade'), config: RhythmSerenadeConfigSchema }),
  z.object({ minigameId: z.literal('lumberjack'), config: LumberjackConfigSchema }),
  z.object({ minigameId: z.literal('writer'), config: WriterConfigSchema }),
]);
export type MinigameConfig = z.infer<typeof MinigameConfigSchema>;

// --- Per-game client submissions (client -> server) -------------------------

export const MemoryMatchSubmissionSchema = z.object({
  pairsMatched: z.number().int().min(0),
  moves: z.number().int().min(0),
  timeMs: z.number().int().min(0),
});
export type MemoryMatchSubmission = z.infer<typeof MemoryMatchSubmissionSchema>;

export const TimingMeterSubmissionSchema = z.object({
  /** Per-round accuracy in [0..1], where 1 is a perfect hit in the target zone. */
  rounds: z.array(z.object({ accuracy: z.number().min(0).max(1) })).min(1).max(20),
});
export type TimingMeterSubmission = z.infer<typeof TimingMeterSubmissionSchema>;

export const LoreQuizSubmissionSchema = z.object({
  answers: z
    .array(z.object({ questionId: z.string(), choiceIndex: z.number().int().min(0) }))
    .min(1),
});
export type LoreQuizSubmission = z.infer<typeof LoreQuizSubmissionSchema>;

export const SweetAndSourSubmissionSchema = z.object({
  placements: z
    .array(
      z.object({
        cardId: z.string(),
        tray: z.enum(['adore', 'avoid', 'meh']),
        confidence: z.number().min(0).max(1).default(0.5),
        swipeMs: z.number().int().min(0).default(0),
      }),
    )
    .min(1)
    .max(20),
});
export type SweetAndSourSubmission = z.infer<typeof SweetAndSourSubmissionSchema>;

export const TwoTruthsSubmissionSchema = z.object({
  rounds: z
    .array(
      z.object({
        roundId: z.string(),
        accusedStatementId: z.string(),
        confidence: z.enum(['low', 'medium', 'high']),
      }),
    )
    .min(1)
    .max(12),
});
export type TwoTruthsSubmission = z.infer<typeof TwoTruthsSubmissionSchema>;

export const RhythmSerenadeSubmissionSchema = z.object({
  taps: z
    .array(z.object({ slotIndex: z.number().int().min(0), offsetMs: z.number() }))
    .max(64),
  totalMs: z.number().int().min(0),
});
export type RhythmSerenadeSubmission = z.infer<typeof RhythmSerenadeSubmissionSchema>;

export const LumberjackSubmissionSchema = z.object({
  /** Per-swing accuracy in [0..1], where 1 is a perfect hit on the grain. The
   *  server derives the combo + score from this raw sequence — the client never
   *  claims a combo or a score. */
  swings: z.array(z.object({ accuracy: z.number().min(0).max(1) })).min(1).max(20),
});
export type LumberjackSubmission = z.infer<typeof LumberjackSubmissionSchema>;

export const WriterSubmissionSchema = z.object({
  /** Exactly what the player typed. The SERVER scores it against its held copy of the
   *  passage (the answer key) AND times the run from its own clock, so the client can
   *  neither claim an accuracy/score nor fake how long it took — a paste is instant, so
   *  it can't forge a human typing pace. */
  typed: z.string().max(4000),
});
export type WriterSubmission = z.infer<typeof WriterSubmissionSchema>;

export const MinigameSubmissionSchema = z.discriminatedUnion('minigameId', [
  z.object({ minigameId: z.literal('memory_match'), submission: MemoryMatchSubmissionSchema }),
  z.object({ minigameId: z.literal('timing_meter'), submission: TimingMeterSubmissionSchema }),
  z.object({ minigameId: z.literal('lore_quiz'), submission: LoreQuizSubmissionSchema }),
  z.object({ minigameId: z.literal('sweet_and_sour'), submission: SweetAndSourSubmissionSchema }),
  z.object({ minigameId: z.literal('two_truths_a_lie'), submission: TwoTruthsSubmissionSchema }),
  z.object({ minigameId: z.literal('rhythm_serenade'), submission: RhythmSerenadeSubmissionSchema }),
  z.object({ minigameId: z.literal('lumberjack'), submission: LumberjackSubmissionSchema }),
  z.object({ minigameId: z.literal('writer'), submission: WriterSubmissionSchema }),
]);
export type MinigameSubmission = z.infer<typeof MinigameSubmissionSchema>;

/** Static metadata describing each registered minigame (for listings/UI). */
export const MinigameInfoSchema = z.object({
  id: MinigameIdSchema,
  title: z.string(),
  description: z.string(),
  targetStats: z.array(z.string()),
  rewardsCharacter: z.boolean(),
  /** Where this surfaces: a bonding game lives in the Arcade; a `job` is paid skill
   *  work and lives in the Work app. Omitted = 'date' (bonding). */
  mode: z.enum(['date', 'job']).optional(),
  /** Job games only: the career skill this builds (see shared `career.ts`). */
  skill: z.string().optional(),
  /** Job games only: XP granted to {@link skill}, scaled by the play's score. */
  skillXp: z.number().int().nonnegative().optional(),
  /** Job games only: skill this is gated behind (locked until {@link requiresLevel}). */
  requiresSkill: z.string().optional(),
  /** Job games only: minimum level of {@link requiresSkill} to unlock. */
  requiresLevel: z.number().int().min(0).optional(),
});
export type MinigameInfo = z.infer<typeof MinigameInfoSchema>;
